// <auto-generated />
using System;
using Brädhörnan_laboration.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Brädhörnan_laboration.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260614162910_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Brädhörnan_laboration.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("AverageGameLength")
                        .HasColumnType("int");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int");

                    b.Property<int>("GameAvailability")
                        .HasColumnType("int");

                    b.Property<string>("GameDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GameMeetingId")
                        .HasColumnType("int");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gamegenre")
                        .HasColumnType("int");

                    b.Property<int>("MaximumNumberOfPlayer")
                        .HasColumnType("int");

                    b.Property<int>("MinimumNumberOfPlayer")
                        .HasColumnType("int");

                    b.HasKey("GameId");

                    b.HasIndex("GameMeetingId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Brädhörnan_laboration.Models.GameMeeting", b =>
                {
                    b.Property<int>("GameMeetingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaximumNumberOfParticipants")
                        .HasColumnType("int");

                    b.Property<int?>("ResponsibleMemberNumber")
                        .HasColumnType("int");

                    b.HasKey("GameMeetingId");

                    b.HasIndex("ResponsibleMemberNumber");

                    b.ToTable("GameMeetings");
                });

            modelBuilder.Entity("Brädhörnan_laboration.Models.Member", b =>
                {
                    b.Property<int>("MemberNumber")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GameMeetingId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("MemberNumber");

                    b.HasIndex("GameMeetingId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Brädhörnan_laboration.Models.Game", b =>
                {
                    b.HasOne("Brädhörnan_laboration.Models.GameMeeting", null)
                        .WithMany("PlannedGames")
                        .HasForeignKey("GameMeetingId");
                });

            modelBuilder.Entity("Brädhörnan_laboration.Models.GameMeeting", b =>
                {
                    b.HasOne("Brädhörnan_laboration.Models.Member", "Responsible")
                        .WithMany()
                        .HasForeignKey("ResponsibleMemberNumber");

                    b.Navigation("Responsible");
                });

            modelBuilder.Entity("Brädhörnan_laboration.Models.Member", b =>
                {
                    b.HasOne("Brädhörnan_laboration.Models.GameMeeting", null)
                        .WithMany("Participants")
                        .HasForeignKey("GameMeetingId");
                });

            modelBuilder.Entity("Brädhörnan_laboration.Models.GameMeeting", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("PlannedGames");
                });
#pragma warning restore 612, 618
        }
    }
}
